### ISSUE TITLE
AttributeError: module 'base64' has no attribute 'decodestring' with Python 3.9.2

### ISSUE THREAD

**Issue by githuzzel** [awegg/landroidcc#6]
2022-08-22 11:13:40 __init__ _api_authentificate INFO     Successfully logged in
Traceback (most recent call last):
  File "/home/raspi/python/landi.py", line 15, in <module>
    landroid.connect(xxxx", "yyyyy")
  File "/usr/local/lib/python3.9/dist-packages/landroidcc/__init__.py", line 74, in connect
    self._connectmqtt()
  File "/usr/local/lib/python3.9/dist-packages/landroidcc/__init__.py", line 135, in _connectmqtt
    pkcs12 = base64.decodestring(self._api_certificate["pkcs12"].encode())
AttributeError: module 'base64' has no attribute 'decodestring'

**Comment by githuzzel** [comment]
after update with latest version it's working. 
At pip is not the latest version
